spring.application.name=DemoSecond
spring.mvc.view.prefix=/web-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.datasource.url=jdbc:mysql://localhost:3306/mockdb
spring.datasource.username=root
spring.datasource.password= Vik@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql= true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect